import { describe, it } from 'vitest';

import { ABNORMAL_PRIVILEGED_FIXTURE, E02_RUNTIME_EXECUTION_AUTHORIZED, EEP_TEST_IDS, EVIDENCE_LEVEL } from '../fixtures/catalog';

const d = E02_RUNTIME_EXECUTION_AUTHORIZED ? describe : describe.skip;

d(`${EEP_TEST_IDS.PARTIAL} / audit / marker / counts [${EVIDENCE_LEVEL.L3_INTEGRATION}]`, () => {
  it(`${EEP_TEST_IDS.AUDIT_MISS}: ${ABNORMAL_PRIVILEGED_FIXTURE} → FAIL_CLOSED PARTIAL_DURABLE_STATE`, () => {});
  it(`${EEP_TEST_IDS.MARKER_MISS}: ${ABNORMAL_PRIVILEGED_FIXTURE} → FAIL_CLOSED MARKER_MISSING`, () => {});
  it(`${EEP_TEST_IDS.COUNT_VOTER}: ${ABNORMAL_PRIVILEGED_FIXTURE} → VOTER_COUNT_MISMATCH`, () => {});
  it(`${EEP_TEST_IDS.COUNT_RESOLUTION}: ${ABNORMAL_PRIVILEGED_FIXTURE} → RESOLUTION_COUNT_MISMATCH`, () => {});
  it(`${EEP_TEST_IDS.COUNT_MOTION}: ${ABNORMAL_PRIVILEGED_FIXTURE} → MOTION_COUNT_MISMATCH`, () => {});
});
